version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "testeautenticacao"
    ports:
      - "3306:3306"
        #volumes:
        #- .:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 80:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge
